service: run-app-api

package:
  patterns:
    - dist/**

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1

  environment:
    MONGO_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    COGNITO_REGION: us-east-2
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}

functions:
  api:
    handler: dist/lambda.handler
    timeout: 30
    memorySize: 512

    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
